exec-once=nm-applet
exec-once=waybar
exec-once=swaybg -m fill -i ~/.config/mango/wallpapers/tree.png
exec-once=/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1

#clipboard
exec-once=wl-paste --type text --watch cliphist store
