windowrule=width:900,height:600,appid:org.pulseaudio.pavucontrol,isfloating:1,title=pavucontrol
windowrule=width:900,height:600,appid:localsend,isfloating:1,title=localsend
windowrule=width:900,height:600,appid:org.gnome.baobab,isfloating:1,title=baobab
windowrule=width:900,height:600,appid:waypaper,isfloating:1,title:waypaper
