###########
## MANGO ##
###########

source=~/.config/mango/custom/autostart.conf
source=~/.config/mango/custom/cursor.conf
source=~/.config/mango/custom/decorations.conf
source=~/.config/mango/custom/env.conf
source=~/.config/mango/custom/input.conf
source=~/.config/mango/custom/keybinds.conf
source=~/.config/mango/custom/layout.conf
source=~/.config/mango/custom/monitor.conf
source=~/.config/mango/custom/windowrule.conf
